language: php
sudo: false
dist: trusty

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2

env:
  - WP_VERSION=latest WC_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini || true
  - bash tests/bin/install-wp-tests.sh woocommerce_test root '' localhost $WP_VERSION
  - bash tests/bin/set-woocommerce-version.sh $WC_VERSION
  - composer install --prefer-source

script:
  - |
    php -c ./php.ini vendor/phan/phan/phan --debug;echo
    echo "Exit Status=$?"
